### ISSUE TITLE
What about cybersource ?

### ISSUE THREAD

**Issue by composercodes** [peter-tharwat/Payment-helper#1]
please do you use cybersource ?

**Comment by Mohamed1Gohar** [comment]
It is preferable to rename the function in style  camelCase

**Comment by peter-tharwat** [comment]
@composercodes sorry,  i haven't used it yet

**Comment by peter-tharwat** [comment]
@composercodes yeah nice suggest , you can rename all of them and make a pull request :+1:

**Comment by peter-tharwat** [comment]
@Mohamed1Gohar  yeah nice suggest , you can rename all of them and make a pull request +1
