### ISSUE TITLE
what main clac_new_amount

### ISSUE THREAD

**Issue by Mohamed1Gohar** [peter-tharwat/Payment-helper#3]
public function clac_new_amount($method, $amount)
    {
        if ($method == 'paymob') {
            return floatval($amount+($amount*env('PAYMOB_PERCENTAGE_FEE'))+env('PAYMOB_FIXED_FEE'));
        }

**Comment by peter-tharwat** [comment]
clac_new_amount : if you are adding some fees to your client - you can calculate_new_amount :+1:
